# Auto-generated by PlantCompiler from AgentPlant output
# System: cstr
# Do not edit by hand unless you know the AgentMPC plugin contract.
import numpy as np
from backend_core.AgentMPC.dynamics.base import BaseDynamics, SystemConfig

# --- user-provided dynamics (sanitized for numpy) ---
import numpy as np

def dynamics(t, x, u):
    q, V, CA0, T0, Tc0 = 1, 1, 1, 350, 300
    k0, E_R, dH, rho, Cp = 7.2e10, 8750, -2e5, 1000, 0.239
    UA, rhoc, Cpc, Vc = 5e4, 1000, 1, 1
    CA, T, Tc = x[0], x[1], x[2]
    r = k0 * np.exp(-E_R/T) * CA
    xdot = [q/V*(CA0 - CA) - r,
            q/V*(T0 - T) - dH/(rho*Cp)*r + UA/(V*rho*Cp)*(Tc - T),
            u/Vc*(Tc0 - Tc) + UA/(Vc*rhoc*Cpc)*(T - Tc)]
    return np.array(xdot)

# --- auto-generated config ---
def create_config() -> SystemConfig:
    return SystemConfig(
        n_states=3,
        n_inputs=1,
        params={'q': 1.0, 'V': 1.0, 'CA0': 1.0, 'T0': 350.0, 'Tc0': 300.0, 'k0': 72000000000.0, 'E_R': 8750.0, 'dH': -200000.0, 'rho': 1000.0, 'Cp': 0.239, 'UA': 50000.0, 'rhoc': 1000.0, 'Cpc': 1.0, 'Vc': 1.0},
        state_names=['CA', 'T', 'Tc'],
        input_names=['u'],
        default_initial_state=np.array([0.8, 324.0, 300.0]),
        default_target=np.array([0.5, 340.0, 305.0]),
    )

class CstrDynamics(BaseDynamics):
    def dynamics(self, x: np.ndarray, u: np.ndarray) -> np.ndarray:
        # Always pass 1-D float arrays. AgentPlant python_code is expected to
        # index u[0], u[1], ... (never treat u as a bare Python float).
        x_arr = np.asarray(x, dtype=float).reshape(-1)
        u_arr = np.atleast_1d(np.asarray(u, dtype=float).reshape(-1))
        out = dynamics(0.0, x_arr, u_arr)
        out_arr = np.atleast_1d(np.asarray(out, dtype=float)).reshape(-1)
        if out_arr.size != 3:
            raise ValueError(
                f"dynamics returned shape {out_arr.shape}, expected (3,)"
            )
        return out_arr
