# Auto-generated by PlantCompiler from AgentPlant output
# System: DC-DC Boost Converter
# Do not edit by hand unless you know the AgentMPC plugin contract.
import numpy as np
from backend_core.AgentMPC.dynamics.base import BaseDynamics, SystemConfig

# --- user-provided dynamics (sanitized for numpy) ---
import numpy as np

def dynamics(t, x, u):
    i_L = x[0]  # inductor current (A)
    v_out = x[1]  # output voltage (V)
    D = u[0]  # duty cycle (0 to 1)
    V_in = 12.0  # input voltage (V)
    V_out_target = 48.0  # target output voltage (V)
    R_L = 0.1  # inductor ESR (ohm)
    R_C = 0.05  # capacitor ESR (ohm)

    # Inductor dynamics
    di_L_dt = (V_in - v_out) / R_L  # change in inductor current (A/s)

    # Output voltage dynamics
    dv_out_dt = (D * V_in - v_out) / (R_C + R_L)  # change in output voltage (V/s)

    dx = np.array([di_L_dt, dv_out_dt])
    return dx

# --- auto-generated config ---
def create_config() -> SystemConfig:
    return SystemConfig(
        n_states=2,
        n_inputs=1,
        params={},
        state_names=['x1', 'x2'],
        input_names=['u1'],
        default_initial_state=np.array([0.0, 0.0]),
        default_target=np.array([0.0, 0.0]),
    )

class DCDCBoostConverterDynamics(BaseDynamics):
    def dynamics(self, x: np.ndarray, u: np.ndarray) -> np.ndarray:
        # Always pass 1-D float arrays. AgentPlant python_code is expected to
        # index u[0], u[1], ... or scalar u.
        x_arr = np.asarray(x, dtype=float).reshape(-1)
        u_arr = np.atleast_1d(np.asarray(u, dtype=float).reshape(-1))
        if u_arr.size == 0:
            u_arr = np.zeros(1)
        u_arg = u_arr[0] if u_arr.size == 1 else u_arr
        try:
            out = dynamics(0.0, x_arr, u_arg)
        except (TypeError, IndexError):
            out = dynamics(0.0, x_arr, u_arr)
        if isinstance(out, (list, tuple)):
            try:
                out_arr = np.asarray(out, dtype=float).reshape(-1)
            except ValueError:
                out_arr = np.array([float(np.squeeze(v)) for v in out], dtype=float).reshape(-1)
        else:
            out_arr = np.atleast_1d(np.asarray(out, dtype=float)).reshape(-1)
        if out_arr.size != 2:
            raise ValueError(
                f"dynamics returned shape {out_arr.shape}, expected (2,)"
            )
        return out_arr
