# Auto-generated by PlantCompiler from AgentPlant output
# System: DC-DC Boost Converter
# Do not edit by hand unless you know the AgentMPC plugin contract.
import numpy as np
from backend_core.AgentMPC.dynamics.base import BaseDynamics, SystemConfig

# --- user-provided dynamics (sanitized for numpy) ---
def dynamics(t, x, u):
    dx0 = x[1]
    dx1 = -x[0] + u
    return [dx0, dx1]

# --- auto-generated config ---
def create_config() -> SystemConfig:
    return SystemConfig(
        n_states=2,
        n_inputs=1,
        params={},
        state_names=['x1', 'x2'],
        input_names=['u'],
        default_initial_state=np.array([0.0, 0.0]),
        default_target=np.array([0.0, 0.0]),
    )

class DCDCBoostConverterDynamics(BaseDynamics):
    def dynamics(self, x: np.ndarray, u: np.ndarray) -> np.ndarray:
        # Always pass 1-D float arrays. AgentPlant python_code is expected to
        # index u[0], u[1], ... or scalar u.
        x_arr = np.asarray(x, dtype=float).reshape(-1)
        u_arr = np.atleast_1d(np.asarray(u, dtype=float).reshape(-1))
        if u_arr.size == 0:
            u_arr = np.zeros(1)
        u_arg = u_arr[0] if u_arr.size == 1 else u_arr
        try:
            out = dynamics(0.0, x_arr, u_arg)
        except TypeError:
            out = dynamics(0.0, x_arr, u_arr)
        out_arr = np.atleast_1d(np.asarray(out, dtype=float)).reshape(-1)
        if out_arr.size != 2:
            raise ValueError(
                f"dynamics returned shape {out_arr.shape}, expected (2,)"
            )
        return out_arr
