# Auto-generated by PlantCompiler from AgentPlant output
# System: maglev
# Do not edit by hand unless you know the AgentMPC plugin contract.
import numpy as np
from backend_core.AgentMPC.dynamics.base import BaseDynamics, SystemConfig

# --- user-provided dynamics (sanitized for numpy) ---
import numpy as np

def dynamics(t, x, u):
    m, g, L, R, k = 0.05, 9.81, 0.01, 1.0, 0.0001
    z, v, i = x[0], x[1], x[2]
    F_mag = k * i**2 / (z**2 + 0.001)
    z_dot = v
    v_dot = g - F_mag / m
    i_dot = (u - R * i - k * i * v / (z**2 + 0.001)) / L
    return np.array([z_dot, v_dot, i_dot])

# --- auto-generated config ---
def create_config() -> SystemConfig:
    return SystemConfig(
        n_states=3,
        n_inputs=1,
        params={'m': 0.05, 'g': 9.81, 'L': 0.01, 'R': 1.0, 'k': 0.0001},
        state_names=['z', 'v', 'i'],
        input_names=['u'],
        default_initial_state=np.array([0.05, 0.0, 0.0]),
        default_target=np.array([0.02, 0.0, 0.0]),
    )

class MaglevDynamics(BaseDynamics):
    def dynamics(self, x: np.ndarray, u: np.ndarray) -> np.ndarray:
        # Always pass 1-D float arrays. AgentPlant python_code is expected to
        # index u[0], u[1], ... (never treat u as a bare Python float).
        x_arr = np.asarray(x, dtype=float).reshape(-1)
        u_arr = np.atleast_1d(np.asarray(u, dtype=float).reshape(-1))
        if u_arr.size == 0:
            u_arr = np.zeros(1)
        u_arg = u_arr[0] if u_arr.size == 1 else u_arr
        try:
            out = dynamics(0.0, x_arr, u_arg)
        except TypeError:
            out = dynamics(0.0, x_arr, u_arr)
        out_arr = np.atleast_1d(np.asarray(out, dtype=float)).reshape(-1)
        if out_arr.size != 3:
            raise ValueError(
                f"dynamics returned shape {out_arr.shape}, expected (3,)"
            )
        return out_arr
